services:
  add_service:
    container_name: add_service
    build: ./calc
    # ports:                            <--- commented because communication is handle internally by nginx reverse proxy
      # - "8081:8080"
  subtract_service:
    container_name: subtract_service
    build: ./calc
    # ports:                            <--- commented because communication is handle internally by nginx reverse proxy
      # - "8082:8080"
  multiply_service:
    container_name: multiply_service
    build: ./calc
    # ports:                            <--- commented because communication is handle internally by nginx reverse proxy
      # - "8083:8080"
  divide_service:
    container_name: divide_service
    build: ./calc
    # ports:                            <--- commented because communication is handle internally by nginx reverse proxy
      # - "8084:8080"
  api_gateway:
    container_name: api_gateway
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      # Mount the custom nginx.conf file
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount a custom directory for additional server blocks (optional, good practice)
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
      # Mount your static web files
      - ./nginx/html:/usr/share/nginx/html:ro
    restart: always
